# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Test-Compiles`
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:runtime-requirement    [ :on "perl 5.008"^^:CpanId ];
	:runtime-requirement    [ :on "Test::More 0.96"^^:CpanId ];
	:runtime-requirement    [ :on "Exporter::Shiny 1.000000"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

